### ISSUE TITLE
Add username before autocomment

### ISSUE THREAD

**Issue by jdd-software** [SOBotics/Userscripts#13]
As Yunnosch suggested in chat https://chat.stackoverflow.com/transcript/message/42437794#42437794, add username of OP to comment.

The benefit is that it gets less "auto" and it's clear that OP is addressed by comment (it's gets more personal and maybe also more nice).

We increase the chance that OP reads and understand the comment

**Comment by double-fault** [comment]
Just to make it clear for anyone else, this issue is talking about the "Natty Reporter" userscript (at least that is what I understood from the chat transcript).

**Comment by double-fault** [comment]
@jdd-software Wouldn't it be more appropriate if this was added to the auto comment script instead (the one not made by SOBotics)?

**Comment by BaumMitAugen** [comment]
@Fortunate-MAN the flagging scripts don't go through the auto comment script, they post directly. So both would have to include it.

In general, I'm not opposed to this, but what is the longest allowed username in characters and how long is our longest auto-comment? If that's not an issue, we can change it, should be easy enough.

**Comment by jdd-software** [comment]
It's an idea if anyone have fun doing it, probably it could be useful also for Advanced Flagging and auto-comment, hence all scripts could be update.

**Comment by rjrudman** [comment]
@BaumMitAugen Based on a SEDE query, the longest display name is 36 characters

**Comment by Yunnosch** [comment]
Thanks for creating this issue.
I do not know how to prove it, but I am the same Yunnosch.
So if there are any questions, ask me.

Concerning the name length problem:
I did some simulation (by editing the autocomments) and yes, some of them are so long that at least the "Welcome to StackOverflow, NAME. However, this ...." does not fit.

I found that the comment could be rephrased to save a few characters and make room. It is however sacrificing something of the teaching and clarity...

The first compromise I can think of is to use the terser version "NAME, this ..." also for new accounts.

Background: I imagine using the welcome-version for comments by accounts younger than a week.
This partially is able to help with the "SO is not a welcoming place" currently going around. I hope this is neutral without actually agreeing or contradicting, the idea is older than this activity. Just adding a welcome to new accounts could be considered reason enough, I hope.

Otherwise, determining the available space and more or less brutally shortening the name woudl probably still be on the right track.

Maybe asking here for proposals of shorter but still appropriate comments is the way.

**Comment by BaumMitAugen** [comment]
@Yunnosch I suppose the comment where this would be most relevant is the 'NAA low rep" one. This is  written by Shog himself and I personally like it as it is, too. I would not really like to shorten it just to make room for some greeting, and just prepending some possibly butchered username does not really sound too useful to me either.

So if we can't fit in some meaningful greeting, moderately long names and the entire Shog comment, I don't think this would be a good change.

**Comment by jdd-software** [comment]
Related to NAA, The current comment of Shog9 is nice, but it miss indication what OP should do (if the comment is correct), self-delete the answer.

It could be an interesting experiment to try with a comment both addressing OP directly and indicating action to take if comment is correct. Now it says "ask a new question,", but it does not state "and delete this"

Naturally we need to consider that the comment may be wrong and also how we can get statistics related to OP self-deletion frequency on type of comment. If anyone has idea on what the modify comment could be, feel free to drop a "comment"

Something like:

> Petter Friberg, this does not provide an answer to the question. You can search for similar questions, or refer to the related and linked questions on the right-hand side of the page to find an answer. If you have a related but different question, ask a new question, include a link to this question to help provide context and delete this answer. See: Ask questions, get answers, no distractions.

**Comment by BaumMitAugen** [comment]
First of all, changing the advice or wording in the comment is kind of orthogonal to the question about the greeting at hand unless it's about shortening the comment to make room for a greeting.

Now about the proposed change of wording: I don't like telling beginners in the <50 rep range to delete their post. They are too likely to be too easily intimidated into deleting an incorrectly handled fp.

Additionally, the risk of us getting it wrong is highest on borderline posts, which would benefit most from additional eyes, be it from the LQQ or a mod. 

And as the clear-cut cases everyone gets right every time are trivial to review anyway, I'm opposed to adding that advice for very new users.

Finally, back to the main topic: it has been brought to my attention that the NAA <50rep comment leaves space for 149 more characters. Even after subtracting the 36 characters for the longest username, that should probably suffice to add a greeting with the name; and I think it's the most important comment in this regard (maybe together with "Thanks", which should be investigated).

So in my opinion, adding the greeting to the two comments mentioned above would cover the most important cases and would be a change I would be fine with.

**Comment by Yunnosch** [comment]
I would be absolutely fine to add the greeting only to those comments which are short enough anyway.
Should any other comment for any reason be edited and happen to be shorter afterwards, prepending the greeting would be adequate I assume.

The same is true for too long names, instead of butchering them omitting them is perfectly fine.

When I mentioned shortening existing comments, I thought of slightly more compact phrasings of practically the same comtent. When I wrote "sacrificing" I only meant the additional level of "unmisunderstandability" which using a few additional words usually allows. All content aspects where kept.
Should comments with rephrasing proposals be welcome, I will contribute.

**Comment by BaumMitAugen** [comment]
Alright, that sounds fine to me. I would say the NAA <50 and "thanks" comments are most important, but the rest can be checked too where it makes sense.

Going forward, a PR is welcome, otherwise this lands on my ~~pile~~ list of stuff to do after I handed in my thesis.

Also, for consistency, it would make sense to raise a similar issue on the Advanced Flagging repository if @rjrudman agrees.

**Comment by rjrudman** [comment]
@BaumMitAugen Yep, I'm happy to keep consistency between scripts

**Comment by double-beep** [comment]
Since this has been implemented in Advanced Flagging, and Advanced Flagging has superseded Natty reporter, I am closing this.
